dataset_target_path : "/home/jkmetko/RubymineProjects/"
numberOfDownloadAttemptsBeforeFailure : 3
delayBetweenAnotherDownloadAttempt : 10
fileMaxSizeInBytes : 1000000


maximumSubsequentGoogleGEOSearchFailures : 5