dataset_target_path : "/Users/alexostrovsky/Downloads/"
numberOfDownloadAttemptsBeforeFailure : 3
delayBetweenAnotherDownloadAttempt : 10
fileMaxSizeInBytes : 1000000


maximumSubsequentGoogleGEOSearchFailures : 5